elasticsearch.yml: xpack settings added only if es_enable_xpack
Prevent the following exception:
    java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed